--create table person
--(
--   id integer not null,
--   name varchar(255) not null,
--   location varchar(255),
--   dateOfBirth timestamp,
--   primary key (id)
--);

INSERT INTO PERSON (ID, NAME, LOCATION, DATE_OF_BIRTH) VALUES (100011, 'Ram', 'Vizianagaram', CURRENT_DATE);
INSERT INTO PERSON (ID, NAME, LOCATION, DATE_OF_BIRTH) VALUES (10006, 'Naveen', 'Vizag', CURRENT_DATE);
INSERT INTO PERSON (ID, NAME, LOCATION, DATE_OF_BIRTH) VALUES (10007, 'Raj', 'Anantapur', CURRENT_DATE);
INSERT INTO PERSON (ID, NAME, LOCATION, DATE_OF_BIRTH) VALUES (10008, 'Raj', 'Guntur', CURRENT_DATE);

INSERT INTO COURSE (ID, NAME, CREATED_DATE_TIME, LAST_UPDATED_DATE_TIME) VALUES (10001, 'SpringBoot', CURRENT_DATE, CURRENT_DATE);
INSERT INTO COURSE (ID, NAME, CREATED_DATE_TIME, LAST_UPDATED_DATE_TIME) VALUES (10002, 'Devops', CURRENT_DATE, CURRENT_DATE);
INSERT INTO COURSE (ID, NAME, CREATED_DATE_TIME, LAST_UPDATED_DATE_TIME) VALUES (10003, 'Python', CURRENT_DATE, CURRENT_DATE);
INSERT INTO COURSE (ID, NAME, CREATED_DATE_TIME, LAST_UPDATED_DATE_TIME) VALUES (10004, 'Java', CURRENT_DATE, CURRENT_DATE);

INSERT INTO PASSPORT (ID, NUMBER) VALUES (30001, 'E34567');
INSERT INTO PASSPORT (ID, NUMBER) VALUES (30002, 'F34567');
INSERT INTO PASSPORT (ID, NUMBER) VALUES (30003, 'B34567');
INSERT INTO PASSPORT (ID, NUMBER) VALUES (30004, 'K34567');

INSERT INTO STUDENT (ID, NAME, PASSPORT_ID) VALUES (20001, 'Ram', 30001);
INSERT INTO STUDENT (ID, NAME, PASSPORT_ID) VALUES (20002, 'Naveen', 30002);
INSERT INTO STUDENT (ID, NAME, PASSPORT_ID) VALUES (20003, 'Raj', 30003);
INSERT INTO STUDENT (ID, NAME, PASSPORT_ID) VALUES (20004, 'Manu', 30004);

INSERT INTO REVIEWS (ID, RATING, DESCRIPTION) VALUES (40001, '5', 'Awesome');
INSERT INTO REVIEWS (ID, RATING, DESCRIPTION) VALUES (40002, '4', 'Informative');
INSERT INTO REVIEWS (ID, RATING, DESCRIPTION) VALUES (40003, '4', 'Great');
INSERT INTO REVIEWS (ID, RATING, DESCRIPTION) VALUES (40004, '3', 'Not Bad');